/* Writes a ready-to-run Blender Python script for a mechanism, ported from
   the C tool's src/export.c.

   One cylinder per pairwise link edge and one empty per joint, plus a keyframe
   per sample so the mechanism ANIMATES in Blender exactly as it does here.
   The motion comes from simulating a private CLONE, so exporting never
   disturbs what is on screen. A driven mechanism is sampled over one full
   revolution of its fastest motor so the animation loops cleanly; a motorless
   one over a few seconds of gravity. If it binds partway, sampling stops at
   the bind.

   Convention: 1 mechanism world unit = 1 mm. */

import * as M from "./mechanism.js?v=7a60899b";
import * as S from "./solver.js?v=7a60899b";

export const EXPORT_FRAMES = 120;

/* Seconds of motion to sample when nothing drives the mechanism and it is
   just falling under gravity. */
const GRAVITY_SAMPLE_SECONDS = 3.0;
/* Upper bound on the simulation step while sampling. Recorded frames can be
   far apart in time (a slow motor makes one revolution take many seconds) and
   stepping that coarsely would let the solver lose the mechanism's branch, so
   each sample is reached via several small steps. */
const MAX_SUBSTEP_SECONDS = 1 / 240;

const f4 = (x) => x.toFixed(4);

function drivenPeriodSeconds(m) {
  let fastest = 0;
  for (const l of m.links) {
    if (!l.alive || !l.isDriven) continue;
    fastest = Math.max(fastest, Math.abs(l.motorSpeedDegS));
  }
  return fastest <= 0 ? 0 : 360 / fastest;
}

export function exportBlenderScript(m, params) {
  /* Index the connectors we actually export, so each frame's position row
     lines up with the joint list regardless of deleted (tombstoned) ids. */
  const jointIds = [];
  for (let i = 0; i < m.connectors.length; i++) {
    if (m.connectors[i].alive) jointIds.push(i);
  }
  const jointCount = jointIds.length;

  const sim = M.clone(m);
  S.freeze(sim);

  const p = { ...params, gravity: { ...params.gravity } };
  const period = drivenPeriodSeconds(sim);
  const driven = period > 0;
  const duration = driven ? period : GRAVITY_SAMPLE_SECONDS;
  if (!driven && !M.hasDrivenLink(sim) && p.gravity.x === 0 && p.gravity.y === 0) {
    /* Nothing would move at all; match the app, which runs a motorless
       mechanism under gravity. */
    p.gravity = { x: 0, y: 400 };
  }

  const frameDt = duration / EXPORT_FRAMES;
  const substeps = Math.max(1, Math.ceil(frameDt / MAX_SUBSTEP_SECONDS));
  const substepDt = frameDt / substeps;

  const samples = [];
  let jammed = false;
  for (let fr = 0; fr < EXPORT_FRAMES; fr++) {
    if (fr > 0) {
      for (let s = 0; s < substeps; s++) S.advance(sim, substepDt, p);
      if (S.hasLengthViolation(sim, p.lengthTolAbs, p.lengthTolRel)) {
        jammed = true;
        break; /* stop at the bind; don't record impossible geometry */
      }
    }
    samples.push(jointIds.map((cid) => ({ x: sim.connectors[cid].pos.x, y: sim.connectors[cid].pos.y })));
  }
  const recorded = samples.length;

  const out = [];
  out.push(
    "import bpy",
    "import mathutils",
    "",
    "# Generated by Linkage Design (mechanism export).",
    "# Convention: 1 mechanism world unit = 1 mm.",
    "# Press Space in Blender to play the animation.",
    "",
    "ROD_RADIUS_MM = 3.0  # link/rod cylinder radius -- edit to taste before running",
    "JOINT_MARKER_RADIUS_MM = ROD_RADIUS_MM * 1.5",
    ""
  );

  out.push(`FRAME_COUNT = ${recorded}`);
  out.push(
    `DURATION_SECONDS = ${(duration * ((recorded > 1 ? recorded - 1 : 1) / (EXPORT_FRAMES - 1))).toFixed(6)}`
  );
  if (jammed) out.push("# NOTE: the mechanism bound up partway; the animation stops where it jammed.");
  out.push("");

  /* Joint names, in the same order as each frame's position row. */
  out.push("JOINTS = [");
  for (const cid of jointIds) {
    const anchor = m.connectors[cid].isAnchor;
    out.push(`    ("${anchor ? "Anchor" : "Joint"}_${cid}", ${anchor ? "True" : "False"}),`);
  }
  out.push("]", "");

  /* Rods, referring to joints by their index in JOINTS. */
  out.push("RODS = [");
  /* Pairs already emitted, so a rail that doubles as a link is not written twice. */
  const joined = new Set();
  for (let li = 0; li < m.links.length; li++) {
    const l = m.links[li];
    if (!l.alive) continue;
    const k = l.connectorIds.length;
    for (let i = 0; i < k; i++) {
      for (let j = i + 1; j < k; j++) {
        const ci = l.connectorIds[i], cj = l.connectorIds[j];
        const slotI = jointIds.indexOf(ci), slotJ = jointIds.indexOf(cj);
        if (slotI < 0 || slotJ < 0) continue;
        out.push(`    ("Link${li}_c${ci}c${cj}", ${slotI}, ${slotJ}),`);
        joined.add(ci < cj ? `${ci}:${cj}` : `${cj}:${ci}`);
      }
    }
  }

  /* A slider's rail is a real part you would machine, so it goes into the rig
     as a rod like any other -- named Rail so it is identifiable in the
     outliner. Skipped when the two rail joints are already joined by a link
     (a pin running in that link's own slot), which would otherwise export the
     same bar twice. */
  for (const sl of M.liveSliders(m)) {
    const key = sl.railAId < sl.railBId
      ? `${sl.railAId}:${sl.railBId}` : `${sl.railBId}:${sl.railAId}`;
    if (joined.has(key)) continue;
    const slotA = jointIds.indexOf(sl.railAId), slotB = jointIds.indexOf(sl.railBId);
    if (slotA < 0 || slotB < 0) continue;
    out.push(`    ("Rail_c${sl.railAId}c${sl.railBId}", ${slotA}, ${slotB}),`);
    joined.add(key);
  }
  out.push("]", "");

  /* One row of joint positions per animation frame. */
  out.push("FRAMES = [");
  for (const row of samples) {
    out.push("    [" + row.map((q) => `(${f4(q.x)},${f4(q.y)})`).join(",") + "],");
  }
  out.push("]", "");

  out.push(
    "scene = bpy.context.scene",
    "scene.unit_settings.system = 'METRIC'",
    "scene.unit_settings.length_unit = 'MILLIMETERS'",
    "scene.frame_start = 1",
    "scene.frame_end = max(FRAME_COUNT, 1)",
    "if FRAME_COUNT > 1 and DURATION_SECONDS > 0.0:",
    "    # Play back at the same rate the mechanism actually runs.",
    "    scene.render.fps = 60",
    "    scene.render.fps_base = 60.0 * DURATION_SECONDS / (FRAME_COUNT - 1)",
    "",
    "",
    "def mm(v):",
    "    return v / 1000.0",
    "",
    "",
    "def make_joint(name, is_anchor):",
    "    bpy.ops.object.empty_add(",
    "        type='PLAIN_AXES' if is_anchor else 'SPHERE',",
    "        radius=mm(JOINT_MARKER_RADIUS_MM), location=(0.0, 0.0, 0.0))",
    "    obj = bpy.context.object",
    "    obj.name = name",
    "    return obj",
    "",
    "",
    "def make_rod(name):",
    "    # Unit-depth cylinder: its length is set per frame via scale.z,",
    "    # which also lets variable-length links animate correctly.",
    "    bpy.ops.mesh.primitive_cylinder_add(radius=mm(ROD_RADIUS_MM), depth=1.0,",
    "                                        location=(0.0, 0.0, 0.0))",
    "    obj = bpy.context.object",
    "    obj.name = name",
    "    obj.rotation_mode = 'QUATERNION'",
    "    return obj",
    "",
    "",
    "joints = [make_joint(name, is_anchor) for (name, is_anchor) in JOINTS]",
    "rods = [(make_rod(name), i, j) for (name, i, j) in RODS]",
    "",
    "for frame_index, positions in enumerate(FRAMES):",
    "    frame = frame_index + 1",
    "    for obj, (x, y) in zip(joints, positions):",
    "        obj.location = (mm(x), mm(y), 0.0)",
    "        obj.keyframe_insert('location', frame=frame)",
    "    for obj, i, j in rods:",
    "        p0 = mathutils.Vector((mm(positions[i][0]), mm(positions[i][1]), 0.0))",
    "        p1 = mathutils.Vector((mm(positions[j][0]), mm(positions[j][1]), 0.0))",
    "        direction = p1 - p0",
    "        length = direction.length",
    "        obj.location = (p0 + p1) / 2.0",
    "        if length > 1e-12:",
    "            obj.rotation_quaternion = direction.to_track_quat('Z', 'Y')",
    "        obj.scale = (1.0, 1.0, max(length, 1e-9))",
    "        obj.keyframe_insert('location', frame=frame)",
    "        obj.keyframe_insert('rotation_quaternion', frame=frame)",
    "        obj.keyframe_insert('scale', frame=frame)",
    "",
    "def iter_fcurves(action):",
    "    # Blender <4.4 exposes action.fcurves directly; 4.4+ moved them",
    "    # into slotted actions (layers -> strips -> channelbags).",
    "    fcurves = getattr(action, 'fcurves', None)",
    "    if fcurves is not None:",
    "        for fcurve in fcurves:",
    "            yield fcurve",
    "        return",
    "    for layer in getattr(action, 'layers', []):",
    "        for strip in getattr(layer, 'strips', []):",
    "            for channelbag in getattr(strip, 'channelbags', []):",
    "                for fcurve in channelbag.fcurves:",
    "                    yield fcurve",
    "",
    "",
    "# Constant-speed motion should not ease in and out between samples.",
    "# The motion is already baked into the keyframes, so treat this as a",
    "# nicety: never let an API change here break the whole import.",
    "try:",
    "    for obj in joints + [rod for (rod, _i, _j) in rods]:",
    "        action = obj.animation_data.action if obj.animation_data else None",
    "        if action is None:",
    "            continue",
    "        for fcurve in iter_fcurves(action):",
    "            for kp in fcurve.keyframe_points:",
    "                kp.interpolation = 'LINEAR'",
    "except Exception as exc:",
    "    print('Linkage Design: could not set linear interpolation (%s); '",
    "          'the animation is still correct.' % exc)",
    "",
    "scene.frame_set(1)",
    "print('Linkage Design: built %d joints, %d rods, %d frames.'",
    "      % (len(joints), len(rods), FRAME_COUNT))"
  );

  return out.join("\n") + "\n";
}
